In [49]:
import requests
from bs4 import BeautifulSoup
import openpyxl
source=requests.get('https://www.gfmag.com/global-data/economic-data/worlds-richest-and-poorest-countries')
soup=BeautifulSoup(source.text, 'html.parser')

In [50]:
list=soup.find('table',border='0').find('tbody')

In [51]:
x=list.find_all('tr')
len(x)

194

In [52]:
val=[]
for rows in x:
    val.append(rows.text.strip().replace('\n','    '))

In [53]:
val

['1    Ireland    145,196',
 '2    Luxembourg    142,490',
 '3    Singapore    133,895',
 '4    Qatar    124,848',
 '5    Macao SAR    89,558',
 '6    United Arab Emirates    88,221',
 '7    Switzerland    87,963',
 '8    Norway    82,655',
 '9    United States    80,035',
 '10    San Marino    78,926',
 '11    Brunei Darussalam    75,583',
 '12    Hong Kong SAR    74,598',
 '13    Denmark    73,386',
 '14    Taiwan    73,344',
 '15    Netherlands    72,973',
 '16    Iceland    69,779',
 '17    Austria    69,502',
 '18    Andorra    68,998',
 '19    Germany    66,132',
 '20    Sweden    65,842',
 '21    Belgium    65,501',
 '22    Australia    65,366',
 '23    Saudi Arabia    64,836',
 '24    Malta    61,939',
 '25    Finland    60,897',
 '26    Guyana    60,648',
 '27    Bahrain    60,596',
 '28    Canada    60,177',
 '29    France    58,828',
 '30    South Korea    56,706',
 '31    United Kingdom    56,471',
 '32    Israel    54,997',
 '33    Cyprus    54,611',
 '34    Italy    54,216',
 '35    New Zealand    54,046',
 '36    Kuwait    53,037',
 '37    Slovenia    52,641',
 '38    Japan    51,809',
 '39    Czech Republic    50,961',
 '40    Aruba    49,627',
 '41    Spain    49,448',
 '42    Lithuania    49,266',
 '43    Estonia    46,385',
 '44    Poland    45,343',
 '45    Portugal    44,708',
 '46    The Bahamas    43,913',
 '47    Hungary    43,907',
 '48    Puerto Rico    43,845',
 '49    Croatia    42,531',
 '50    Oman    42,188',
 '51    Romania    41,634',
 '52    Slovak Republic    41,515',
 '53    Turkey    41,412',
 '54    Latvia    40,256',
 '55    Panama    40,177',
 '56    Seychelles    39,662',
 '57    Greece    39,478',
 '58    Malaysia    36,847',
 '59    Maldives    36,358',
 '60    Russia    34,837',
 '61    Kazakhstan    32,688',
 '62    Trinidad and Tobago    32,054',
 '63    Bulgaria    32,006',
 '64    St. Kitts and Nevis    29,662',
 '65    Chile    27,608',
 '66    Mauritius    29,164',
 '67    Uruguay    28,470',
 '68    Montenegro    27,761',
 '69    Argentina    27,261',
 '70    Costa Rica    26,422',
 '71    Dominican Republic    25,896',
 '72    Serbia    25,432',
 '73    Libya    24,559',
 '74    Antigua and Barbuda    24,012',
 '75    Mexico    23,820',
 '76    Belarus    23,447',
 '77    China    23,382',
 '78    Thailand    22,675',
 '79    Georgia    21,923',
 '80    North Macedonia    21,111',
 '81    Grenada    20,075',
 '82    Turkmenistan    19,974',
 '83    Bosnia and Herzegovina    19,604',
 '84    Iran    19,548',
 '85    Armenia    19,489',
 '86    Colombia    19,460',
 '87    Botswana    19,398',
 '88    Gabon    19,197',
 '89    Albania    19,029',
 '90    Barbados    18,858',
 '91    Brazil    18,686',
 '92    Azerbaijan    18,669',
 '93    Equatorial Guinea    18,510',
 '94    St. Lucia    18,435',
 '95    Suriname    18,427',
 '96    St. Vincent and the Grenadines    17,793',
 '97    Egypt    16,979',
 '98    Moldova    16,840',
 '99    Palau    16,394',
 '100    Peru    16,132',
 '101    South Africa    16,091',
 '102    Indonesia    15,855',
 '103    Fiji    15,727',
 '104    Kosovo    15,620',
 '105    Paraguay    15,578',
 '106    Mongolia    14,939',
 '107    Vietnam    14,458',
 '108    Sri Lanka    14,223',
 '109    Bhutan    14,170',
 '110    Dominica    14,161',
 '111    Ukraine    13,901',
 '112    Ecuador    13,513',
 '113    Algeria    13,507',
 '114    Tunisia    13,270',
 '115    Iraq    12,927',
 '116    Jordan    12,893',
 '117    Jamaica    12,887',
 '118    El Salvador    11,647',
 '119    Eswatini    11,492',
 '120    Namibia    11,440',
 '121    Philippines    11,420',
 '122    Nauru    11,342',
 '123    Belize    10,939',
 '124    Guatemala    10,546',
 '125    Morocco    10,460',
 '126    Bolivia    10,327',
 '127    Uzbekistan    10,308',
 '128    Lao P.D.R.    9,801',
 '129    Cabo Verde    9,661',
 '130    India    9,073',
 '131    Bangladesh    8,663',
 '132    Venezuela    8,028',
 '133    Nicaragua    7,601',
 '134    Mauritania    7,437',
 '135    Honduras    7,228',
 '136    Angola    7,222',
 '137    Tonga    7,125',
 "138    Côte d'Ivoire    7,011",
 '139    Ghana    6,974',
 '140    Djibouti    6,894',
 '141    Pakistan    6,836',
 '142    West Bank and Gaza    6,688',
 '143    Kenya    6,569',
 '144    Samoa    6,324',
 '145    Kyrgyz Republic    6,250',
 '146    Nigeria    6,178',
 '147    Cambodia    6,092',
 '148    Tuvalu    5,797',
 '149    Tajikistan    5,293',
 '150    Republic of the Congro    5,155',
 '151    Myanmar    5,132',
 '152    Nepal    5,101',
 '153    São Tomé and Príncipe    4,874',
 '154    Marshall Islands    4,669',
 '155    Cameroon    4,665',
 '156    Papua New Guinea    4,516',
 '157    Senegal    4,515',
 '158    Sudan    4,471',
 '159    Benin    4,300',
 '160    Zambia    4,041',
 '161    Micronesia    3,931',
 '162    Ethiopia    3,724',
 '163    Timor-Leste    3,637',
 '164    Tanzania    3,600',
 '165    Comoros    3,463',
 '166    Lesotho    3,251',
 '167    Haiti    3,248',
 '168    Uganda    3,224',
 '169    Guinea    3,218',
 '170    Rwanda    3,090',
 '171    Guinea-Bissau    3,072',
 '172    Vanuatu    3,001',
 '173    The Gambia    2,804',
 '174    Togo    2,754',
 '175    Burkina Faso    2,726',
 '176    Mali    2,656',
 '177    Zimbabwe    2,627',
 '178    Solomon Islands    2,414',
 '179    Kirbati    2,381',
 '180    Eritrea    2,188',
 '181    Sierra Leone    2,082',
 '182    Yemen    2,042',
 '183    Madagascar    1,916',
 '184    Liberia    1,788',
 '185    Chad    1,787',
 '186    Malawi    1,682',
 '187    Niger    1,600',
 '188    Mozambique    1,556',
 '189    Democratic Republic of the Congo    1,474',
 '190    Somalia    1,374',
 '191    Central Afrian Republic    1,127',
 '192    Burundi    891',
 '193    South Sudan    516',
 '—    Afghanistan, Lebanon, Syria, Ukraine    N.A.']